# Generated by Django 3.1.4 on 2021-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookvehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
                ('drop', models.CharField(max_length=100)),
                ('truck', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='emailid',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
