# Generated by Django 3.1.4 on 2021-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mno', models.IntegerField(max_length=10)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
