# Generated by Django 3.1.4 on 2021-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210316_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('licenseno', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckname', models.CharField(max_length=20)),
                ('trucktype', models.CharField(max_length=20)),
                ('registrationnumber', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('mobilenumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proceed',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
