# Generated by Django 3.1.4 on 2021-03-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210319_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='licenseno',
            new_name='licensenumber',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='phoneno',
            new_name='phonnumber',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='mobilenumber',
            new_name='owner_mobile_number',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='registrationnumber',
            new_name='registration_number',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='truckname',
            new_name='truck_name',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='trucktype',
            new_name='truck_type',
        ),
    ]
