# Generated by Django 3.1.4 on 2021-03-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210319_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuplocation', models.CharField(max_length=100)),
                ('droplocation', models.CharField(max_length=100)),
                ('trucktype', models.CharField(max_length=100)),
                ('pickupdate', models.CharField(max_length=100)),
                ('goodstype', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
