# Generated by Django 3.1.4 on 2021-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10)),
                ('cardnumber', models.IntegerField(max_length=14)),
                ('holdername', models.CharField(max_length=20)),
                ('exp_month', models.IntegerField(max_length=2)),
                ('exp_year', models.IntegerField(max_length=2)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
