# Generated by Django 3.1.4 on 2021-04-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
