# Generated by Django 3.1.4 on 2021-04-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210404_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceed',
            name='labour',
            field=models.CharField(default='', max_length=10),
        ),
    ]
