# Generated by Django 3.1.4 on 2021-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_proceed_labour'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='labour',
            field=models.CharField(default='', max_length=10),
        ),
    ]
